name: Call the reusable deploy

on:
  push:
    branches:
      - "*"   # triggers on every branch

jobs:
  call-reusable:
    uses: ANKPS/password_rotator_pipeline/.github/workflows/handle_deployment.yml@PRNAKL-16_disco_GF

