name: Call the reusable deploy

on:
  push:
    branches:
      - "*"   # triggers on every branch

jobs:
  call-reusable:
    uses: PRNAKL/password_rotator_pipeline/.github/workflows/handle_deployment.yml@PRNAKL-8_feature_GF
    # This is an experimental branch
    permissions:
      id-token: write
      contents: read
    secrets:                             # forward repo secrets to the reusable workflow
      DEPLOY_LAMBDA_PERMISSIONS: ${{ secrets.DEPLOY_LAMBDA_PERMISSIONS }}
