name: Call the reusable deploy

on:
  push:
    branches:
      - "*"   # triggers on every branch

jobs:
  call-reusable:
    uses: PRNAKL/password_rotator_pipeline/.github/workflows/handle_deployment.yml@PRNAKL-16_disco_GF # This is an experimental branch
    permissions:
      id-token: write
      contents: read
