name: Handle Deployment

on:
  workflow_call:
    inputs:
      lambda_function_name:
        description: "The name of the Lambda function to invoke"
        required: true
        type: string
      aws_region:
        description: "AWS region to deploy to"
        required: false
        default: "us-east-1"
        type: string

jobs:
  call-pylint:
    uses: ./.github/workflows/lint.yml

  call-tests:
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [call-pylint, call-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name ${{ inputs.lambda_function_name }} \
            --payload '{}' \
            response.json
          cat response.json
